/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CustomClock {
    }
    interface MyArray {
        "dataItems": string[];
        "isComplete": boolean;
        "itemValue": string;
        "showPrompt": () => Promise<number>;
        "thingToDo": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
        "myMethod": () => Promise<number>;
    }
}
declare global {
    interface HTMLCustomClockElement extends Components.CustomClock, HTMLStencilElement {
    }
    var HTMLCustomClockElement: {
        prototype: HTMLCustomClockElement;
        new (): HTMLCustomClockElement;
    };
    interface HTMLMyArrayElement extends Components.MyArray, HTMLStencilElement {
    }
    var HTMLMyArrayElement: {
        prototype: HTMLMyArrayElement;
        new (): HTMLMyArrayElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "custom-clock": HTMLCustomClockElement;
        "my-array": HTMLMyArrayElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CustomClock {
    }
    interface MyArray {
        "dataItems"?: string[];
        "isComplete"?: boolean;
        "itemValue"?: string;
        "thingToDo"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "custom-clock": CustomClock;
        "my-array": MyArray;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "custom-clock": LocalJSX.CustomClock & JSXBase.HTMLAttributes<HTMLCustomClockElement>;
            "my-array": LocalJSX.MyArray & JSXBase.HTMLAttributes<HTMLMyArrayElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
